### ISSUE TITLE
Module build problems (npm rebuild or npm install) Python: invalid syntax

### ISSUE THREAD

**Issue by fightforlife** [RaymondMouthaan/node-red-docker#17]
### What are the steps to reproduce?
Run: npm install node-red-node-serialport 
or 
Run: npm rebuild (to test any module)

### What happens?
If there are no prebuilt binaries available:
The built process finishes with an python error because of a bad syntax.
This doesnt seem to be module specific!

```
bash-4.4$ npm i node-red-node-serialport

> @serialport/bindings@2.0.8 install /usr/src/node-red/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.16.3 runtime=node arch=arm libc=musl platform=linux)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:198:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Linux 4.19.57-sunxi
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/node-red/node_modules/@serialport/bindings
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### What do you expect to happen?

the npm modules should be built sucessfull

### Please tell us about your environment:

- [X] Node-RED version: 0.20.7
- [X] node.js version: 10.16.3
- [X] npm version:
- [X] Platform/OS: RaymondMouthaan/node-red-docker:latest on Ubuntu 19.04
- [X] Browser: Chrome 77.0

**Comment by RaymondMouthaan** [comment]
@fightforlife, 

Reason for this is most probably because latest has python3 installed and not python2, which is required by node-red-node-serialport to compile.

I tried tag `latest-10-python2` and added Alpine build-base package manually to the container using `apk add --no-cache build-base`. Unfortunately that did not solve the issue. I am not sure whats the issue, perhaps @knolleary or @dceejay could have a look at the log below?


```
2019-09-14T13:31:44.285Z Install : node-red-node-serialport 0.8.6

2019-09-14T13:31:44.283Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-node-serialport@0.8.6
2019-09-14T13:31:56.716Z [out] 
2019-09-14T13:31:56.716Z [out] > @serialport/bindings@2.0.8 install /data/node_modules/@serialport/bindings
2019-09-14T13:31:56.716Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2019-09-14T13:31:56.716Z [out] 
2019-09-14T13:31:58.352Z [err] prebuild-install
2019-09-14T13:31:58.354Z [err]  
2019-09-14T13:31:58.355Z [err] WARN
2019-09-14T13:31:58.356Z [err]  
2019-09-14T13:31:58.357Z [err] install
2019-09-14T13:31:58.358Z [err]  No prebuilt binaries found (target=10.16.3 runtime=node arch=arm libc=musl platform=linux)
2019-09-14T13:32:01.504Z [out] make: Entering directory '/data/node_modules/@serialport/bindings/build'
2019-09-14T13:32:01.510Z [out]   CXX(target) Release/obj.target/bindings/src/serialport.o
2019-09-14T13:32:04.530Z [err] In file included from ../src/./serialport.h:6,
2019-09-14T13:32:04.530Z [err]                  from ../src/serialport.cpp:1:
2019-09-14T13:32:04.530Z [err] ../../../nan/nan.h: In function 'void Nan::AsyncQueueWorker(Nan::AsyncWorker*)':
2019-09-14T13:32:04.530Z [err] ../../../nan/nan.h:2298:62: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
2019-09-14T13:32:04.530Z [err]      , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
2019-09-14T13:32:04.530Z [err]                                                               ^
2019-09-14T13:32:04.649Z [err] ../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)':
2019-09-14T13:32:04.649Z [err] ../src/serialport.cpp:78:69: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
2019-09-14T13:32:04.649Z [err]    uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen);
2019-09-14T13:32:04.649Z [err]                                                                      ^~~~~~~~~~~~~
2019-09-14T13:32:04.661Z [err] ../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)':
2019-09-14T13:32:04.661Z [err] ../src/serialport.cpp:135:71: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
2019-09-14T13:32:04.661Z [err]    uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_AfterUpdate);
2019-09-14T13:32:04.661Z [err]                                                                        ^~~~~~~~~~~~~~~
2019-09-14T13:32:04.667Z [err] ../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)':
2019-09-14T13:32:04.667Z [err] ../src/serialport.cpp:175:70: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
2019-09-14T13:32:04.667Z [err]    uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterClose);
2019-09-14T13:32:04.667Z [err]                                                                       ^~~~~~~~~~~~~~
2019-09-14T13:32:04.672Z [err] ../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)':
2019-09-14T13:32:04.672Z [err] ../src/serialport.cpp:215:70: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
2019-09-14T13:32:04.672Z [err]    uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterFlush);
2019-09-14T13:32:04.672Z [err]                                                                       ^~~~~~~~~~~~~~
2019-09-14T13:32:04.679Z [err] ../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)':
2019-09-14T13:32:04.679Z [err] ../src/serialport.cpp:270:68: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
2019-09-14T13:32:04.679Z [err]    uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet);
2019-09-14T13:32:04.679Z [err]                                                                     ^~~~~~~~~~~~
2019-09-14T13:32:04.684Z [err] ../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_METHOD_ARGS_TYPE)':
2019-09-14T13:32:04.684Z [err] ../src/serialport.cpp:314:68: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
2019-09-14T13:32:04.684Z [err]    uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet);
2019-09-14T13:32:04.684Z [err]                                                                     ^~~~~~~~~~~~
2019-09-14T13:32:04.697Z [err] ../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan::NAN_METHOD_ARGS_TYPE)':
2019-09-14T13:32:04.697Z [err] ../src/serialport.cpp:363:76: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
2019-09-14T13:32:04.697Z [err]    uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_AfterGetBaudRate);
2019-09-14T13:32:04.697Z [err]                                                                             ^~~~~~~~~~~~~~~~~~~~
2019-09-14T13:32:04.707Z [err] ../src/serialport.cpp: In function 'Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)':
2019-09-14T13:32:04.707Z [err] ../src/serialport.cpp:409:70: warning: cast between incompatible function types from 'void (*)(uv_work_t*)' {aka 'void (*)(uv_work_s*)'} to 'uv_after_work_cb' {aka 'void (*)(uv_work_s*, int)'} [-Wcast-function-type]
2019-09-14T13:32:04.707Z [err]    uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain);
2019-09-14T13:32:04.707Z [err]                                                                       ^~~~~~~~~~~~~~
2019-09-14T13:32:04.710Z [err] ../src/serialport.cpp: At global scope:
2019-09-14T13:32:04.710Z [err] ../src/serialport.cpp:430:28: warning: unnecessary parentheses in declaration of 'ToParityEnum' [-Wparentheses]
2019-09-14T13:32:04.710Z [err]  SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {
2019-09-14T13:32:04.710Z [err]                             ^
2019-09-14T13:32:04.712Z [err] ../src/serialport.cpp:449:30: warning: unnecessary parentheses in declaration of 'ToStopBitEnum' [-Wparentheses]
2019-09-14T13:32:04.712Z [err]  SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {
2019-09-14T13:32:04.712Z [err]                               ^
2019-09-14T13:32:04.716Z [err] In file included from ../../../nan/nan.h:54,
2019-09-14T13:32:04.716Z [err]                  from ../src/./serialport.h:6,
2019-09-14T13:32:04.716Z [err]                  from ../src/serialport.cpp:1:
2019-09-14T13:32:04.716Z [err] /usr/src/node-red/.node-gyp/10.16.3/include/node/node.h:573:43: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
2019-09-14T13:32:04.716Z [err]        (node::addon_register_func) (regfunc),                          \
2019-09-14T13:32:04.716Z [err]                                            ^
2019-09-14T13:32:04.716Z [err] /usr/src/node-red/.node-gyp/10.16.3/include/node/node.h:607:3: note: in expansion of macro 'NODE_MODULE_X'
2019-09-14T13:32:04.716Z [err]    NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
2019-09-14T13:32:04.716Z [err]    ^~~~~~~~~~~~~
2019-09-14T13:32:04.716Z [err] ../src/serialport.cpp:483:1: note: in expansion of macro 'NODE_MODULE'
2019-09-14T13:32:04.716Z [err]  NODE_MODULE(serialport, init);
2019-09-14T13:32:04.716Z [err]  ^~~~~~~~~~~
2019-09-14T13:32:04.841Z [err] In file included from /usr/src/node-red/.node-gyp/10.16.3/include/node/node.h:63,
2019-09-14T13:32:04.841Z [err]                  from ../../../nan/nan.h:54,
2019-09-14T13:32:04.841Z [err]                  from ../src/./serialport.h:6,
2019-09-14T13:32:04.841Z [err]                  from ../src/serialport.cpp:1:
2019-09-14T13:32:04.841Z [err] /usr/src/node-red/.node-gyp/10.16.3/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]':
2019-09-14T13:32:04.841Z [err] /usr/src/node-red/.node-gyp/10.16.3/include/node/node_object_wrap.h:84:78:   required from here
2019-09-14T13:32:04.841Z [err] /usr/src/node-red/.node-gyp/10.16.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<node::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
2019-09-14T13:32:04.841Z [err]                 reinterpret_cast<Callback>(callback), type);
2019-09-14T13:32:04.841Z [err]                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-09-14T13:32:04.885Z [err] /usr/src/node-red/.node-gyp/10.16.3/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
2019-09-14T13:32:04.885Z [err] ../../../nan/nan_object_wrap.h:65:61:   required from here
2019-09-14T13:32:04.885Z [err] /usr/src/node-red/.node-gyp/10.16.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
2019-09-14T13:32:10.040Z [out]   CXX(target) Release/obj.target/bindings/src/serialport_unix.o
2019-09-14T13:32:10.558Z [err] ../src/serialport_unix.cpp:24:10: fatal error: linux/serial.h: No such file or directory
2019-09-14T13:32:10.558Z [err]  #include <linux/serial.h>
2019-09-14T13:32:10.558Z [err]           ^~~~~~~~~~~~~~~~
2019-09-14T13:32:10.561Z [err] compilation terminated.
2019-09-14T13:32:10.574Z [err] make: *** [bindings.target.mk:102: Release/obj.target/bindings/src/serialport_unix.o] Error 1
2019-09-14T13:32:10.574Z [out] make: Leaving directory '/data/node_modules/@serialport/bindings/build'
2019-09-14T13:32:10.579Z [err] gyp
2019-09-14T13:32:10.580Z [err]  
2019-09-14T13:32:10.581Z [err] ERR! build error
2019-09-14T13:32:10.581Z [err]  
2019-09-14T13:32:10.583Z [err] gyp
2019-09-14T13:32:10.583Z [err]  ERR! stack
2019-09-14T13:32:10.583Z [err]  Error: `make` failed with exit code: 2
2019-09-14T13:32:10.583Z [err] gyp ERR!
2019-09-14T13:32:10.583Z [err]  stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
2019-09-14T13:32:10.584Z [err] gyp ERR!
2019-09-14T13:32:10.584Z [err]  stack     at ChildProcess.emit (events.js:198:13)
2019-09-14T13:32:10.584Z [err] gyp 
2019-09-14T13:32:10.584Z [err] ERR! stack
2019-09-14T13:32:10.584Z [err]      at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
2019-09-14T13:32:10.585Z [err] gyp
2019-09-14T13:32:10.585Z [err]  ERR! System
2019-09-14T13:32:10.586Z [err]  Linux 4.19.58-v7+
2019-09-14T13:32:10.586Z [err] gyp
2019-09-14T13:32:10.586Z [err]  ERR! 
2019-09-14T13:32:10.587Z [err] command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2019-09-14T13:32:10.587Z [err] gyp
2019-09-14T13:32:10.587Z [err]  
2019-09-14T13:32:10.588Z [err] ERR! cwd /data/node_modules/@serialport/bindings
2019-09-14T13:32:10.588Z [err] gyp 
2019-09-14T13:32:10.588Z [err] ERR! node -v
2019-09-14T13:32:10.588Z [err]  v10.16.3
2019-09-14T13:32:10.589Z [err] gyp
2019-09-14T13:32:10.589Z [err]  ERR! 
2019-09-14T13:32:10.589Z [err] node-gyp -v v3.8.0
2019-09-14T13:32:10.589Z [err] gyp 
2019-09-14T13:32:10.589Z [err] ERR! not ok
2019-09-14T13:32:10.589Z [err]  
2019-09-14T13:32:11.224Z [err] npm
2019-09-14T13:32:11.224Z [err]  
2019-09-14T13:32:11.225Z [err] ERR!
2019-09-14T13:32:11.225Z [err]  
2019-09-14T13:32:11.225Z [err] code
2019-09-14T13:32:11.226Z [err]  ELIFECYCLE
2019-09-14T13:32:11.227Z [err] npm
2019-09-14T13:32:11.227Z [err]  
2019-09-14T13:32:11.228Z [err] ERR!
2019-09-14T13:32:11.228Z [err]  
2019-09-14T13:32:11.228Z [err] errno
2019-09-14T13:32:11.229Z [err]  1
2019-09-14T13:32:11.234Z [err] npm
2019-09-14T13:32:11.234Z [err]  
2019-09-14T13:32:11.235Z [err] ERR!
2019-09-14T13:32:11.235Z [err]  @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2019-09-14T13:32:11.235Z [err] npm
2019-09-14T13:32:11.235Z [err]  
2019-09-14T13:32:11.236Z [err] ERR!
2019-09-14T13:32:11.236Z [err]  Exit status 1
2019-09-14T13:32:11.237Z [err] npm
2019-09-14T13:32:11.238Z [err]  
2019-09-14T13:32:11.238Z [err] ERR!
2019-09-14T13:32:11.238Z [err]  
2019-09-14T13:32:11.239Z [err] npm
2019-09-14T13:32:11.239Z [err]  
2019-09-14T13:32:11.239Z [err] ERR!
2019-09-14T13:32:11.239Z [err]  Failed at the @serialport/bindings@2.0.8 install script.
2019-09-14T13:32:11.240Z [err] npm
2019-09-14T13:32:11.240Z [err]  
2019-09-14T13:32:11.240Z [err] ERR!
2019-09-14T13:32:11.241Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2019-09-14T13:32:11.329Z [err] 
2019-09-14T13:32:11.330Z [err] npm
2019-09-14T13:32:11.331Z [err]  
2019-09-14T13:32:11.331Z [err] ERR!
2019-09-14T13:32:11.331Z [err]  A complete log of this run can be found in:
2019-09-14T13:32:11.332Z [err] npm
2019-09-14T13:32:11.332Z [err]  
2019-09-14T13:32:11.332Z [err] ERR!
2019-09-14T13:32:11.333Z [err]      /usr/src/node-red/.npm/_logs/2019-09-14T13_32_11_270Z-debug.log
```

**Comment by dceejay** [comment]
can you try a manual install from the .node-red directory ? but add the `--unsafe-perm` flag - which allows node-gyp to not drop privilege levels. Also it seems to be looking for serial.h which should come from the linux headers I think - did you do this first ? https://serialport.io/docs/guide-installation#installation-special-cases

**Comment by RaymondMouthaan** [comment]
@dceejay, thanks for the suggestions, I guess the images are missing required packages to compile the node and possibly other nodes as well. For serial port, I'll try the suggestions you gave.

However, generally speaking, is Python 2 required to compile nodes? Is it not Python 3 ready? For [#127](https://github.com/node-red/node-red-docker/pull/127), I made the Python 3 as default Python version, but if this will not work for most of the compiling, maybe Python 2 should be the default, knowing its EOF 1 Januari 2020.

Any thoughts are welcome :-)

**Comment by dceejay** [comment]
It's the node-gyp program that is used to compile nodes - and that seems to be struggling to get itself sorted on python 3. And then of course lots of other nodes (like serialport) rely on it.

The "errors" in your log look more like bcrypt compile warnings (which is the other node we try to compile - but there is a pure js backup and it's only a optional dependancy. So yes the serialport seemed to install correctly... It would be nice if the bcrypt also installed - so maybe there is a lib required for that also - https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#alpine-linux-based-images

**Comment by fightforlife** [comment]
I did not have a lot of time today but I tried the image with the tag: latest-12-python2
When installing serialport over the Webinterface I get a different error: make is missing?

16 Sep 19:45:14 - [info] Installing module: node-red-node-serialport, version: 0.8.6
16 Sep 19:46:39 - [warn] Installation of module node-red-node-serialport failed:
16 Sep 19:46:39 - [warn] ------------------------------------------
16 Sep 19:46:39 - [warn] prebuild-install WARN install No prebuilt binaries found (target=12.10.0 runtime=node arch=arm libc=musl platform=linux)
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:169:21)
gyp ERR! System Linux 4.19.57-sunxi
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/node_modules/@serialport/bindings
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by RaymondMouthaan** [comment]
> It's the node-gyp program that is used to compile nodes - and that seems to be struggling to get itself sorted on python 3. And then of course lots of other nodes (like serialport) rely on it.
> 
> The "errors" in your log look more like bcrypt compile warnings (which is the other node we try to compile - but there is a pure js backup and it's only a optional dependancy. So yes the serialport seemed to install correctly... It would be nice if the bcrypt also installed - so maybe there is a lib required for that also - https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#alpine-linux-based-images

After some reading about node-gyp and Python 3, it seems node-gyp doesn't support Python 3 [ref](https://github.com/nodejs/node-gyp#on-unix). Many issues by many users on there github.

Apparently, because of many nodes rely on node-gyp and therefore on Python 2, it might be better for [#127 - Multi-arch support (arm32v6, arm32v7, arm64v8, amd64](https://github.com/node-red/node-red-docker/pull/127), to set Python 2 as the default instead of Python 3?

Meanwhile I'll have a look at bcrypt.

**Comment by dceejay** [comment]
yes - we will need Python2 until node-gyp gets fixed... and if not we will all be broken when python2 goes away.

**Comment by RaymondMouthaan** [comment]
i'll close this issue, since it is fixed in latest docker images.

**Comment by fightforlife** [comment]
I just tried the "latest" tag, and I still got the same error.
Which tag should be used?
Thanks in advance!

**Comment by RaymondMouthaan** [comment]
> I just tried the "latest" tag, and I still got the same error.
> Which tag should be used?
> Thanks in advance!

you should use latest
- which steps do you take? So i can try to reproduce it

**Comment by fightforlife** [comment]
Sorry! Wrong Alert.
Portainer did not pull the latest "latest" image. After a manual pull everything everythin ist perfect.
I am very happy! Thanks!

**Comment by RaymondMouthaan** [comment]
> Sorry! Wrong Alert.
> Portainer did not pull the latest "latest" image. After a manual pull everything everythin ist perfect.
> I am very happy! Thanks!

That was the first thing i thought about ;) .. glad I could help :)
