### ISSUE TITLE
Errors and Restarting Container

### ISSUE THREAD

**Issue by nicedevil007** [RaymondMouthaan/node-red-docker#20]
Hey Raymond,

I've got a problem since some days now :(
My container is always restarting after a few minutes.

First I thought it is a defect Raspberry Pi because I got other issues with that hardware. But after changing the MicroSD Card everything else is working fine except the node-red container.

```
28 Sep 07:03:25 - [info] [mqtt-broker:698f4472.014554] Connected to broker: mqtt://mosquitto:1883
28 Sep 07:03:25 - [red] Uncaught Exception:
28 Sep 07:03:25 - RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:70:11)
    at checkBounds (internal/buffer.js:41:5)
    at checkInt (internal/buffer.js:60:3)
    at writeU_Int32BE (internal/buffer.js:788:3)
    at Buffer.writeUInt32BE (internal/buffer.js:801:10)
    at Jimp.setPixelColor (/data/node_modules/@jimp/core/dist/index.js:885:24)
    at /data/node_modules/node-red-contrib-valetudo/valetudo-map-png.js:137:35
    at Array.forEach (<anonymous>)
    at Jimp.<anonymous> (/data/node_modules/node-red-contrib-valetudo/valetudo-map-png.js:122:24)
    at Timeout._onTimeout (/data/node_modules/@jimp/core/dist/index.js:331:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
```

**Comment by nicedevil007** [comment]
Ok nvm... think it belongs to the valetudo node :(
I stoped the mqtt broker and then restarted the node-red and was able to uninstall it... now it seems to run again.
